#:kivy 2.3.0

<BaseCard@FloatLayout>:
    size_hint: None, None
    canvas.before:
        # Drop shadow
        Color:
            rgba: 0, 0, 0, 0.16
        RoundedRectangle:
            pos: self.x + dp(4), self.y - dp(4)
            size: self.size
            radius: [dp(20), ]
        # Main card background
        Color:
            rgba: root.bg_color if hasattr(root, "bg_color") else (0.78, 0.85, 0.68, 0.9)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(20), ]

<StatusCard@BaseCard>:
    title: 'NO_TITLE'
    value: '--'
    ring_color: 0.3, 0.6, 0.3, 0.8
    bg_color: 0.78, 0.85, 0.68, 0.9
    value_font_size: 30
    size: dp(203), dp(345)

    Widget:
        size_hint: None, None
        size: dp(150), dp(150)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        canvas.before:
            Color:
                rgba: root.ring_color
            Line:
                width: dp(5)
                circle: (self.center_x, self.center_y, self.width / 2)

    Label:
        text: root.title
        font_size: "31sp"
        color: 1, 1, 1, 1
        size_hint_y: None
        height: dp(40)
        pos_hint: {'center_x': 0.5, 'top': 0.95}
        halign: 'center'
        valign: 'middle'
        text_size: self.width, None

    Label:
        text: root.value
        font_size: f"{root.value_font_size}sp"
        color: 1, 1, 1, 1
        size_hint: None, None
        size: dp(100), dp(100)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        halign: 'center'
        valign: 'middle'
        text_size: self.size

<WhiteButton@Button>:
    font_size: "20sp"
    size_hint: None, None
    size: dp(120), dp(40)
    background_normal: ''
    background_color: 0, 0, 0, 0
    color: 0.263, 0.263, 0.263, 1
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(10), ]

<SystemStatusCard@BaseCard>:
    size: dp(436), dp(282)

<PlantListCard@BaseCard>:
    size: dp(203), dp(282)

<AlertCard@BaseCard>:
    size: dp(203), dp(282)

<GreenhouseApp>:
    Image:
        source: 'resources/backgrounds/MAIN_BACKGROUND.png'
        allow_stretch: True
        keep_ratio: False
        size_hint: (1, 1)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            
    # Status Cards
    StatusCard:
        id: temperature_card
        title: "Temperature"
        bg_color: 0.78, 0.85, 0.68, 0.9
        value_font_size: 30
        pos: dp(189), dp(325)

    StatusCard:
        id: humidity_card
        title: "Humidity"
        bg_color: 0.17, 0.25, 0.004, 0.9
        value_font_size: 51
        pos: dp(425), dp(325)

    StatusCard:
        id: soil_moisture_card
        title: "Soil Moisture"
        bg_color: 0.53, 0.65, 0.29, 0.9
        value_font_size: 51
        pos: dp(661), dp(325)

    StatusCard:
        id: light_level_card
        title: "Light Level"
        bg_color: 0.65, 0.78, 0.50, 0.9
        value_font_size: 35
        pos: dp(897), dp(325)

    # System Status Card
    SystemStatusCard:
        id: system_status_card
        bg_color: 0.78, 0.85, 0.68, 0.9
        pos: dp(189), dp(20)

        Label:
            text: "System Status"
            font_size: "31sp"
            color: 1, 1, 1, 1
            size_hint_y: None
            height: dp(40)
            pos_hint: {'center_x': 0.5, 'top': 0.95}
            halign: 'center'
            valign: 'middle'
            text_size: self.width, None

        # Fan Section
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: dp(400), dp(40)
            pos_hint: {'center_x': 0.5, 'center_y': 0.67}
            spacing: dp(20)

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    pos: self.x + dp(30), self.y - dp(10)
                    size: self.width - dp(30), dp(2)

            Widget:
                size_hint: None, None
                size: dp(12), dp(12)
                pos_hint: {'center_x': 0.5, 'center_y': 0.47}
                canvas.before:
                    Color:
                        rgba: app.greenhouse_data.fan_status_color
                    Ellipse:
                        pos: self.pos
                        size: self.size

            Label:
                text: "Fan"
                font_size: "25sp"
                color: 1, 1, 1, 1
                halign: 'left'
                valign: 'middle'
                text_size: self.width, None

            WhiteButton:
                text: "Override"
                # Toggling the fan status updates the property => auto color change
                on_press: app.greenhouse_data.toggle_fan_status()

        # Lighting Section
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: dp(400), dp(40)
            pos_hint: {'center_x': 0.5, 'center_y': 0.43}
            spacing: dp(20)

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                Rectangle:
                    pos: self.x + dp(30), self.y - dp(10)
                    size: self.width - dp(30), dp(2)

            Widget:
                size_hint: None, None
                size: dp(12), dp(12)
                pos_hint: {'center_x': 0.5, 'center_y': 0.47}
                canvas.before:
                    Color:
                        rgba: app.greenhouse_data.lighting_status_color
                    Ellipse:
                        pos: self.pos
                        size: self.size

            Label:
                text: "Lighting"
                font_size: "25sp"
                color: 1, 1, 1, 1
                halign: 'left'
                valign: 'middle'
                text_size: self.width, None

            WhiteButton:
                text: "Override"
                on_press: app.greenhouse_data.toggle_lighting_status()

        # Water Pump Section
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: dp(400), dp(40)
            pos_hint: {'center_x': 0.5, 'center_y': 0.19}
            spacing: dp(20)

            Widget:
                size_hint: None, None
                size: dp(12), dp(12)
                pos_hint: {'center_x': 0.5, 'center_y': 0.47}
                canvas.before:
                    Color:
                        rgba: app.greenhouse_data.water_pump_status_color
                    Ellipse:
                        pos: self.pos
                        size: self.size

            Label:
                text: "Water Pump"
                font_size: "25sp"
                color: 1, 1, 1, 1
                halign: 'left'
                valign: 'middle'
                text_size: self.width, None

            WhiteButton:
                text: "Override"
                on_press: app.greenhouse_data.toggle_water_pump_status()

    # Plant List Card
    PlantListCard:
        id: plant_list_card
        bg_color: 0.17, 0.25, 0.004, 0.9
        pos: dp(661), dp(20)

        Label:
            text: "Plant List"
            font_size: "31sp"
            color: 1, 1, 1, 1
            size_hint_y: None
            height: dp(40)
            pos_hint: {'center_x': 0.5, 'top': 0.95}
            halign: 'center'
            valign: 'middle'
            text_size: self.width, None

        # Total Plants Section
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: dp(180), dp(40)
            pos_hint: {'center_x': 0.5, 'center_y': 0.70}
            spacing: dp(5)
            canvas.before:
                Color:
                    rgba: 0.486, 0.635, 0.302, 0.9
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(5), ]

            Label:
                text: f"Total Plants:    {app.greenhouse_data.total_plants}"
                font_size: "20sp"
                color: 1, 1, 1, 1
                halign: 'left'
                valign: 'middle'
                text_size: self.width, None
                padding_x: dp(10)

        # Total Species Section
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: dp(180), dp(40)
            pos_hint: {'center_x': 0.5, 'center_y': 0.558}
            spacing: dp(5)
            canvas.before:
                Color:
                    rgba: 0.549, 0.682, 0.384, 0.9
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(5), ]

            Label:
                text: f"Total Species:  {app.greenhouse_data.total_species}"
                font_size: "20sp"
                color: 1, 1, 1, 1
                halign: 'left'
                valign: 'middle'
                text_size: self.width, None
                padding_x: dp(10)

        # Available Spots Section
        BoxLayout:
            orientation: 'horizontal'
            size_hint: None, None
            size: dp(180), dp(40)
            pos_hint: {'center_x': 0.5, 'center_y': 0.416}
            spacing: dp(5)
            canvas.before:
                Color:
                    rgba: 0.655, 0.776, 0.502, 0.9
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(5), ]

            Label:
                text: f"Available Spots:   {app.greenhouse_data.available_spots}"
                font_size: "18sp"
                color: 1, 1, 1, 1
                halign: 'left'
                valign: 'middle'
                text_size: self.width, None
                padding_x: dp(10)

        WhiteButton:
            text: "Plant Home"
            size_hint: None, None
            size: dp(150), dp(40)
            pos_hint: {'center_x': 0.5, 'y': 0.15}
            on_release: app.root.current = "PlantHome"

    # Alert Card
    AlertCard:
        id: alert_card
        bg_color: 0.78, 0.85, 0.68, 0.9
        pos: dp(897), dp(20)

        Label:
            text: "Alerts"
            font_size: "31sp"
            color: 1, 1, 1, 1
            size_hint_y: None
            height: dp(40)
            pos_hint: {'center_x': 0.5, 'top': 0.95}
            halign: 'center'
            valign: 'middle'
            text_size: self.width, None

        ScrollView:
            size_hint: 0.7, 0.62
            pos_hint: {'center_x': 0.5, 'center_y': 0.50}
            bar_width: dp(5)
            scroll_type: ['bars', 'content']

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(10), ]

            BoxLayout:
                id: alerts_list
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: dp(30)
                padding: [dp(10), dp(20), dp(10), dp(20)]

                Label:
                    text: "Alert: [color=434343]Water is Getting Low![/color]"
                    font_size: "9sp"
                    markup: True
                    color: 0.2, 0.4, 0.2, 1
                    text_size: self.width, None
                    halign: 'left'
                    valign: 'middle'

                Label:
                    text: "[color=FFA500]Warning:[/color] [color=434343]Temperature below optimal range (12°C)[/color]"
                    font_size: "9sp"
                    markup: True
                    text_size: self.width, None
                    halign: 'left'
                    valign: 'middle'

                Label:
                    text: "[color=FF0000]Critical:[/color] [color=434343]Sudden temperature drop detected![/color]"
                    font_size: "9sp"
                    markup: True
                    text_size: self.width, None
                    halign: 'left'
                    valign: 'middle'

        WhiteButton:
            text: "View All"
            font_size: "18sp"
            size_hint: None, None
            size: dp(100), dp(30)
            pos_hint: {'center_x': 0.5, 'y': 0.05}
            on_press: print("Navigating to Alerts Page")

    # Exit Button
    Button:
        background_normal: ''
        background_down: ''
        background_color: 0, 0, 0, 0
        size_hint: None, None
        width: dp(60)
        height: dp(60)
        pos_hint: {'center_x': 0.04, 'center_y': 0.95}
        padding: dp(10), 0, 0, 0
        on_release: app.stop()
        Image:
            source: 'resources/icons/white_cross.png'
            size_hint: None, None
            size: dp(70), dp(70)
            keep_ratio: True
            allow_stretch: False
            center_x: self.parent.center_x
            center_y: self.parent.center_y
    
    