#:kivy 2.3.0
<SidebarButton@Button>:
    background_normal: ''
    background_color: 0, 0, 0, 0
    icon_source: ''
    selected: False
    canvas.before:
        Color:
            rgba: (0.172, 0.251, 0.004, 0.45) if self.selected else (0, 0, 0, 0)
        RoundedRectangle:
            pos: self.center_x - dp(30), self.center_y - dp(30)
            size: dp(60), dp(60)
            radius: [dp(10), ]
    Image:
        source: root.icon_source
        size_hint: 0.6, 0.6
        center_x: root.center_x
        center_y: root.center_y

<SettingsScreen>:
    name: 'settings'

    FloatLayout:
        Image:
            source: 'resources/backgrounds/Setting_Background.png'
            allow_stretch: True
            keep_ratio: False
            size_hint: 1, 1
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        Label:
            text: 'Greenhouse Settings'
            bold: True
            font_size: '75sp'
            color: 0.2, 0.2, 0.2, 1
            size_hint: None, None
            size: self.texture_size
            pos_hint: {'center_x': 0.5, 'top': 0.95}

        FloatLayout:
            size_hint: 0.58, 0.58
            pos_hint: {'center_x': 0.5, 'top': 0.79}
            
            # This is the text input for the greenhouse name
            BoxLayout:
                size_hint: (None, None)
                pos_hint: {'center_x': 0.5, 'top': 1.00}
                height: dp(60)              
                width: dp(750)            
                padding: [dp(10), dp(0)]    
                spacing: dp(0)
                canvas.before:
                    Color:
                        rgba: 0.78, 0.85, 0.68, 0.9
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(10)]

                TextInput:
                    id: text_input
                    multiline: False
                    font_size: '36sp'    
                    background_normal: ''
                    background_active: ''
                    halign: 'center'
                    background_color: 0, 0, 0, 0 
                    foreground_color: 0, 0, 0, 1
                    cursor_color: 0, 0, 0, 1
                    hint_text: "Greenhouse Name"
                    hint_text_color: 0, 0, 0,1
                    size_hint: (1, 1)
                
            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.48, 0.6
                pos_hint: {'center_x': 0.24, 'top': 0.78}
                canvas.before:
                    Color:
                        rgba: 0.78, 0.85, 0.68, 1  # #C7D9AD
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(10), ]
                
                Label:
                    id: unit_label
                    text: "Units"
                    font_size: '36sp'
                    pos_hint: {'center_x': 0.5}
                    color: 0, 0, 0, 1
                    size_hint: None, None
                    height: dp(40)
                
                FloatLayout:
                    Button:
                        size_hint: None, None
                        size: dp(160), dp(160)
                        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
                        background_normal: ''
                        background_down: ''
                        background_color: 0, 0, 0, 0
                        on_release: root.greenhouse_unit_switch()

                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1  # white
                            RoundedRectangle:
                                pos: self.pos
                                size: self.size
                                radius: [dp(20)]

                    Label:
                        text: "Imperial" if root.greenhouse_unit == "Imperial" else "Metric"
                        font_size: '24sp'
                        color: 0.2, 0.2, 0.2, 1
                        pos_hint: {'center_x': 0.5, 'center_y': 0.75}
                    
                    Label:
                        text: "°F" if root.greenhouse_unit == "Imperial" else "°C"
                        font_size: '48sp'
                        color: 0, 0, 0, 1
                        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            BoxLayout:
                orientation: 'vertical'
                size_hint: 0.48, 0.6
                pos_hint: {'center_x': 0.76, 'top': 0.78}
                canvas.before:
                    Color:
                        rgba: 0.78, 0.85, 0.68, 1  # #C7D9AD
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(10), ]
                
                Label:
                    id: unit_label
                    text: "Layout"
                    font_size: '36sp'
                    pos_hint: {'center_x': 0.5}
                    color: 0, 0, 0, 1
                    size_hint: None, None
                    height: dp(40)
                
                BoxLayout:
                    orientation: 'horizontal'
                    FloatLayout:
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint: None, None
                            size: dp(160), dp(160)
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

                            canvas.before:
                                Color:
                                    rgba: 1, 1, 1, 1  # white
                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [dp(20)]

                        Label:
                            text: "Rows"
                            font_size: '24sp'
                            color: 0.2, 0.2, 0.2, 1
                            pos_hint: {'center_x': 0.5, 'center_y': 0.75}
                        
                        TextInput:
                            id: row_input
                            multiline: False
                            font_size: '48sp'  
                            halign: 'center'
                            background_normal: ''
                            background_active: ''
                            background_color: 0, 0, 0, 0 
                            foreground_color: 0, 0, 0, 1
                            cursor_color: 0, 0, 0, 1
                            hint_text: "Setup"
                            hint_text_color: 0.8, 0.8, 0.8, 1
                            size_hint: (1, 1)
                            pos_hint: {'center_x': 0.5, 'center_y': 0.15}
                            on_text: root.validate_row_input(self.text)

                    FloatLayout:
                        BoxLayout:
                            orientation: 'vertical'
                            size_hint: None, None
                            size: dp(160), dp(160)
                            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

                            canvas.before:
                                Color:
                                    rgba: 1, 1, 1, 1  # white
                                RoundedRectangle:
                                    pos: self.pos
                                    size: self.size
                                    radius: [dp(20)]

                        Label:
                            text: "Columns"
                            font_size: '24sp'
                            color: 0.2, 0.2, 0.2, 1
                            pos_hint: {'center_x': 0.5, 'center_y': 0.75}
                        
                        TextInput:
                            id: col_input
                            multiline: False
                            font_size: '48sp'  
                            halign: 'center'
                            background_normal: ''
                            background_active: ''
                            background_color: 0, 0, 0, 0 
                            foreground_color: 0, 0, 0, 1
                            cursor_color: 0, 0, 0, 1
                            hint_text: "Setup"
                            hint_text_color: 0.8, 0.8, 0.8, 1
                            size_hint: (1, 1)
                            pos_hint: {'center_x': 0.5, 'center_y': 0.15}
                            on_text: root.validate_col_input(self.text)
                        
            # These are the buttons on the bottom of the screen
            BoxLayout:
                orientation: 'horizontal'
                size_hint: None, None
                width: dp(600)
                height: dp(70)
                pos_hint: {'center_x': 0.5, 'center_y': 0.04}
                canvas.before:
                    Color:
                        rgba: 0.78, 0.85, 0.68, 1  # #C7D9AD
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [dp(10), ]
            
                SidebarButton:
                    icon_source: 'resources/icons/home.png'
                    on_release: app.root.current = "home"

                SidebarButton:
                    icon_source: 'resources/icons/leaves.png'
                    on_press: app.root.current = "PlantHome"

                SidebarButton:
                    icon_source: 'resources/icons/analytics.png'
                    on_press: print("Not Implemented Yet!")

                SidebarButton:
                    icon_source: 'resources/icons/nature.png'
                    on_press: print("Not Implemented Yet!")

                SidebarButton:
                    icon_source: 'resources/icons/settings.png'
                    selected: True

            

        